# 定義工作流程名稱
name: CI/CD Pipeline

# 觸發條件：當推送至 main 分支時執行
on:
  push:
    branches:
      - main

# 定義作業
jobs:
  build:
    # 運行環境：使用最新 Ubuntu 系統
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # 檢查出代碼
        uses: actions/checkout@v3

      - name: Simulate build
        # 模擬構建過程（無實際構建腳本）
        run: echo "Generating build artifact"

      - name: Upload artifact
        # 上傳模擬的構建產出作為工件
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .

  deploy-staging:
    # 依賴 build 作業，確保構建完成
    needs: build
    runs-on: ubuntu-latest
    # 指定部署到 staging 環境
    environment: staging
    steps:
      - name: Download artifact
        # 下載構建產出工件
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Deploy to staging
        # 部署到 staging 環境（模擬）
        run: echo "Deploying to staging environment"

  deploy-prod:
    # 依賴 deploy-staging 作業，確保 staging 部署完成
    needs: deploy-staging
    runs-on: ubuntu-latest
    # 指定部署到 prod 環境
    environment: prod
    steps:
      - name: Download artifact
        # 下載構建產出工件
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Deploy to production
        # 部署到 prod 環境（模擬）
        run: echo "Deploying to production environment"

      - name: Simulate manual approval
        # 模擬手動批准步驟
        run: echo "Manual approval completed, proceeding to live deployment"

      - name: Deploy to live
        # 部署到實時環境（模擬）
        run: echo "Deploying to live environment"
